# Generated by Django 6.0.6 on 2026-06-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tasca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titol", models.CharField(max_length=200)),
                ("descripcio", models.TextField(blank=True)),
                ("completada", models.BooleanField(default=False)),
                ("data_creacio", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
