# Generated by Django 6.0.6 on 2026-06-04 16:48

import django.db.models.deletion
from django.db import migrations, models

def crear_aplicacions(apps, schema_editor): 
    Aplicacio = apps.get_model('tasques', 'Aplicacio') 
    noms = [ 
        "CRM Corporatiu", 
        "ERP Central", 
        "Intranet", 
        "Gestor Documental", 
        "Aplicació de Recursos Humans", 
        "Portal de Clients", 
        "E-commerce", 
        "Sistema de Tickets", 
        "Aplicació de Logística", 
        "Quadre de Comandament" 
    ] 
    for nom in noms: 
        Aplicacio.objects.create(nom=nom) 


class Migration(migrations.Migration):

    dependencies = [
        ("tasques", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aplicacio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="tasca",
            name="data_fi_prevista",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tasca",
            name="data_inici",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tasca",
            name="prioritat",
            field=models.CharField(
                choices=[
                    ("baixa", "Baixa"),
                    ("mitjana", "Mitjana"),
                    ("alta", "Alta"),
                    ("critica", "Crítica"),
                ],
                default="mitjana",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tasca",
            name="aplicacio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasques.aplicacio",
            ),
        ),
    ]
