# Generated by Django 6.0.6 on 2026-06-15 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasques", "0003_tasca_usuari"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="tasca",
            name="estat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasques.estat",
            ),
        ),
    ]
