# Generated by Django 6.0.6 on 2026-06-18 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasques", "0004_estat_tasca_estat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("creat_el", models.DateTimeField(auto_now_add=True)),
                (
                    "tasca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="tasques.tasca",
                    ),
                ),
            ],
            options={
                "ordering": ["-creat_el"],
            },
        ),
    ]
