# Generated by Django 6.0.6 on 2026-07-06 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasques", "0005_nota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasca",
            name="data_fi_prevista",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tasca",
            name="data_inici",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
