# Generated by Django 6.0.7 on 2026-07-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasques", "0006_alter_tasca_data_fi_prevista_alter_tasca_data_inici"),
    ]

    operations = [
        migrations.AddField(
            model_name="estat",
            name="color",
            field=models.CharField(default="#6c757d", max_length=7),
        ),
    ]
