# Generated by Django 6.0.7 on 2026-07-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestio_documental", "0001_initial"),
        ("tasques", "0007_estat_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasca",
            name="documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="objectes_relacionats",
                to="gestio_documental.document",
            ),
        ),
    ]
