# Generated by Django 6.0.7 on 2026-07-13 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("fitxer", models.FileField(upload_to="documents/")),
                ("tipus_mime", models.CharField(blank=True, max_length=100)),
                ("mida_bytes", models.PositiveIntegerField(blank=True, null=True)),
                ("descripcio", models.TextField(blank=True)),
                ("etiqueta", models.CharField(blank=True, max_length=50)),
                ("creat", models.DateTimeField(auto_now_add=True)),
                ("modificat", models.DateTimeField(auto_now=True)),
                (
                    "creat_per",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_creats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creat"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fitxer", models.FileField(upload_to="documents/versions/")),
                ("versio", models.PositiveIntegerField()),
                ("creat", models.DateTimeField(auto_now_add=True)),
                (
                    "creat_per",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions_creades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="gestio_documental.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-versio"],
                "unique_together": {("document", "versio")},
            },
        ),
    ]
